def english_keys(data):
    japanese_to_english = {
        "販売スケジュール": "Sales Schedule",
        "販売価格": "Sales Price",
        "最多価格帯": "Most Expensive Price Range",
        "販売戸数": "Number of Units for Sale",
        "間取り": "Layout",
        "専有面積": "Exclusive Area",
        "バルコニー面積": "Balcony Area",
        "管理費": "Management Fee",
        "修繕積立金": "Repair Reserve Fund",
        "修繕積立基金": "Repair Reserve Fund Amount",
        "取引条件有効期限": "Validity Period of Transaction Conditions",
        "所在地": "Location",
        "交通": "Access",
        "総戸数": "Total Number of Units",
        "構造および階数": "Structure and Number of Floors",
        "駐車場": "Parking Lot",
        "完成時期": "Completion Date",
        "引き渡し可能年月": "Available for Delivery",
        "分譲後の権利形態": "Ownership Form after Condominium Sales",
        "管理形態": "Management Form",
        "管理員の勤務形態": "Form of Manager's Working Hours",
        "敷地面積": "Site Area",
        "用途地域": "Land Use Zone",
        "建築確認番号": "Building Confirmation Number",
        "売主": "Seller",
        "販売会社": "Sales Company",
        "施工会社": "Construction Company",
        "管理会社": "Management Company",
        "備考": "Remarks",
        "情報更新日": "Information Update Date",
        "次回更新予定日": "Next Scheduled Update Date",
        "予定最多価格帯": "Planned Most Expensive Price Range",
        "本販売期以降の総販売戸数": "Total Number of Units for Sale after this Sales Period",
        "その他費用": "Other Expenses",
        "販売概要備考": "Sales Overview Remarks",
        "その他、共有施設等": "Other, Shared Facilities, etc.",
        "その他面積": "Other Area",
        "設備": "Facilities",
        "施設費用、償却費": "Facility Expenses, Depreciation Expenses",
        "国土法": "Land Law",
    }

    return [{japanese_to_english.get(key, key): value for key, value in item.items()} for item in data]
